version: "3.3"

services:

  traefik:
    container_name: "traefik"
    image: "traefik:v2.10"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--entrypoints.websecure.address=:443"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/traefikconf/"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefikconf/:/traefikconf/"
      - "/etc/letsencrypt/:/etc/letsencrypt/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  delicalc-build:
    container_name: delicalc-build
    build:
      context: .
    image: delicalc-build

    # volumes:
    #   - "./backend/data/:./backend/data/"

  delicalc-host: # compute.lca4bio-app.indecol.no
    container_name: delicalc-host
    depends_on:
      delicalc-host:
        condition: service_completed_successfully
        restart: true
    labels:
      - "traefik.http.routers.delicalc-host.tls=true"
      - "traefik.http.routers.delicalc-host.rule=Host(`deli-calculator.indecol.no`)"